using System;
using System.Collections.Generic;
using Xunit;

namespace Gitic.Tests
{
    public class GitparserRefactoredTests
    {
        [Fact]
        public void TestGitParserRefactored_ParseCommitRecord_WithValidMetadata()
        {
            IGitParser parser = new GitParser(new GitPatchParser());
            
            // Construct a sample commit record format as it is generated by `git log`
            string sampleOutput = 
                "__GITIC_COMMIT__\n" +
                "abc1234\n" +
                "2026-07-25T08:34:07Z\n" +
                "Alice Smith\n" +
                "alice@example.com\n" +
                "parent123\n" +
                "Implement refactored record metadata parsing\n" +
                "Co-authored-by: Bob <bob@example.com>\n" +
                "__GITIC_NUMSTAT__\n" +
                "5\t3\tsrc/Gitparser.cs\n" +
                "diff --git a/src/Gitparser.cs b/src/Gitparser.cs\n" +
                "@@ -1,3 +1,15 @@\n";

            var commits = parser.ParseGitLog(sampleOutput);
            Assert.Single(commits);

            var commit = commits[0];
            Assert.Equal("abc1234", commit.Hash);
            Assert.Equal("Alice Smith", commit.Author.Name);
            Assert.Equal("alice@example.com", commit.Author.Email);
            Assert.Equal("Implement refactored record metadata parsing\nCo-authored-by: Bob <bob@example.com>", commit.Message);
            Assert.Equal(1, commit.ParentCount);
            
            Assert.Single(commit.Files);
            var file = commit.Files[0];
            Assert.Equal("src/Gitparser.cs", file.Path);
            Assert.Equal(5, file.Added);
            Assert.Equal(3, file.Deleted);

            Assert.Single(commit.CoAuthors);
            Assert.Equal("Bob", commit.CoAuthors[0].Name);
            Assert.Equal("bob@example.com", commit.CoAuthors[0].Email);
        }

        [Fact]
        public void TestGitParserRefactored_ParseCommitRecord_WithInvalidMetadata()
        {
            IGitParser parser = new GitParser(new GitPatchParser());
            
            // Missing author email, parents, message line, etc.
            string sampleOutput = 
                "__GITIC_COMMIT__\n" +
                "abc1234\n" +
                "2026-07-25T08:34:07Z\n" +
                "__GITIC_NUMSTAT__\n" +
                "5\t3\tsrc/Gitparser.cs\n";

            var commits = parser.ParseGitLog(sampleOutput);
            Assert.Empty(commits);
        }
    }
}
